import { Glob } from "bun";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

const GENERATED_FILE = "server/embedded-assets.generated.ts";
const DEFAULT_OUTFILE = process.platform === "win32" ? "build/landrop.exe" : "build/landrop";
const EMPTY_GENERATED_FILE = "// This file is rewritten temporarily by `bun run build:prod`.\n";

const args = parseArgs(process.argv.slice(2));
const outfile = args.outfile ?? process.env.LANDROP_OUTFILE ?? DEFAULT_OUTFILE;
const target = args.target ?? process.env.LANDROP_TARGET ?? currentCompileTarget();

await run(["bun", "run", "build"]);
await writeEmbeddedAssetImports();
await mkdir(dirname(outfile), { recursive: true });

try {
  await run([
    "bun",
    "build",
    "--compile",
    `--target=${target}`,
    "--minify",
    "--asset-naming=[dir]/[name].[ext]",
    "server/main.ts",
    "--outfile",
    outfile,
  ]);
} finally {
  await writeFile(GENERATED_FILE, EMPTY_GENERATED_FILE);
}

console.log(`Built ${outfile}${target ? ` for ${target}` : ""}`);

async function writeEmbeddedAssetImports() {
  const glob = new Glob("dist/**/*");
  const files = [...glob.scanSync({ cwd: ".", onlyFiles: true })].sort();

  if (!files.includes("dist/index.html")) {
    throw new Error("dist/index.html was not produced by the frontend build");
  }

  const imports = files
    .map((file) => `import "../${file}" with { type: "file" };`)
    .join("\n");

  await writeFile(
    GENERATED_FILE,
    `// Generated by scripts/build-production.ts. Do not edit manually.\n${imports}\n`,
  );
}

async function run(command: readonly string[]) {
  const process = Bun.spawn(command, {
    stdout: "inherit",
    stderr: "inherit",
  });
  const exitCode = await process.exited;

  if (exitCode !== 0) {
    throw new Error(`${command.join(" ")} exited with ${exitCode}`);
  }
}

function parseArgs(args: readonly string[]) {
  const parsed: {
    target?: string;
    outfile?: string;
  } = {};

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];

    if (arg === "--target") {
      parsed.target = args[index + 1];
      index += 1;
      continue;
    }

    if (arg?.startsWith("--target=")) {
      parsed.target = arg.slice("--target=".length);
      continue;
    }

    if (arg === "--outfile") {
      parsed.outfile = args[index + 1];
      index += 1;
      continue;
    }

    if (arg?.startsWith("--outfile=")) {
      parsed.outfile = arg.slice("--outfile=".length);
    }
  }

  return parsed;
}

function currentCompileTarget() {
  if (process.platform === "linux" && process.arch === "x64") {
    return "bun-linux-x64";
  }

  if (process.platform === "linux" && process.arch === "arm64") {
    return "bun-linux-arm64";
  }

  if (process.platform === "darwin" && process.arch === "x64") {
    return "bun-darwin-x64";
  }

  if (process.platform === "darwin" && process.arch === "arm64") {
    return "bun-darwin-arm64";
  }

  if (process.platform === "win32" && process.arch === "x64") {
    return "bun-windows-x64";
  }

  if (process.platform === "win32" && process.arch === "arm64") {
    return "bun-windows-arm64";
  }

  throw new Error(`Unsupported compile host: ${process.platform}/${process.arch}`);
}
